run:
  timeout: 5m

linters:
  enable:
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
issues:
  include:
    - EXC0012
    - EXC0014
